language: ruby
#cache: bundler

rvm:
 - 2.6.6
 - ruby-head

env:
  - "RAILS_VERSION=5.2.1"
#  - "RAILS_VERSION=6.0.1"
#  - "RAILS_VERSION=6.1.0"
#  - "RAILS_VERSION=7.0.0"

notifications:
    - false
scripts:
  - bundle exec rspec
after_script:
  - bundle exec rake coveralls:push
