language: ruby

before_install:
 # install bundler 2.x
 - gem install bundler

rvm:
 - 2.6.6
 - ruby-head
gemfile:
 - gemfiles/rails-5.2.gemfile
 - gemfiles/rails-6.0.gemfile


notifications:
    - false
scripts:
  - bundle exec rspec
after_script:
  - bundle exec rake coveralls:push
